### ISSUE TITLE
Introduction of .NET 5 blocked from strict dependency of ChatLib from graphics (WPF) 

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/DDMChat#15]
@marcocappolimases during introduction of .NET 5 I discovered that project ChatLib had a strict reference to the graphic  https://github.com/masesgroup/DDMChat/blob/9ec4fc2a968f2e98b53d80cf9b990eb29aa58315/src/ChatLib/Message.cs#L84

I think the graphic shall be managed only in ChatUI project. I think the property refers to the side where the message shall be shown, anyway the position depends on the receiver point of view and shall be identified using other mechanisms, reported using an enumerator of the ChatLib, at the end shall be translated from the UI using its own methods.

_Originally posted by @mariomastrodicasa in https://github.com/masesgroup/DDMChat/issues/12#issuecomment-868694713_

**Comment by marcocappolimases** [comment]
The VisualMessages Class that contains the dependency was designed to be a ChatUI project class. I moved the class in the ChatUI 
 project and  removed the WPF dependency.
